### ISSUE TITLE
Error: "let*: Symbol's function definition is void: flet"

### ISSUE THREAD

**Issue by dowcet** [spatz/helm-projectile-all#2]
Although `helm-projectile` is working fine, when I run `helm-projectile-all` I just get the error: "let*: Symbol's function definition is void: flet".

**Comment by spatz** [comment]
Probably a missing `(require 'cl)`.
Note that I no longer maintain this package as it was implemented in `helm-projectile` as `helm-projectile-find-file-in-known-projects`, so please use that instead.

**Comment by dowcet** [comment]
OK, thanks!
